### ISSUE TITLE
create_code uses gpt-4 even if set to gpt-3.5

### ISSUE THREAD

**Issue by PhillipRt** [zabirauf/AutoGPT.js#13]
This leads to this error every time if you don't have access to gpt-4:
Error calling API with status code 404 and message "{

"error": {

"message": "The model: `gpt-4` does not exist",

"type": "invalid_request_error",

"param": null,

"code": "model_not_found"

}

}

"

**Comment by zabirauf** [comment]
Thanks for reporting that bug, I’ll look into it.

**Comment by zabirauf** [comment]
@PhillipRt issues should be fixed. I've made the model being used consistent across all plugins based on selection.
