### ISSUE TITLE
Deployment....

### ISSUE THREAD

**Issue by WizKid1968** [zabirauf/AutoGPT.js#14]
I just wanted to know how can I deploy your script to a web server? Thanks in advance.

**Comment by zabirauf** [comment]
@WizKid1968 I’ll work on adding more details in README soon(ish). Currently its deployed using Fly.io. If you want to use Fly then you can follow the instructions here https://github.com/remix-run/indie-stack#deployment on how to deploy.

**Comment by WizKid1968** [comment]
Actually if you can tell me what files need to be included in the build directory, I believe I can successfully deploy the app to Azure.

**Comment by zabirauf** [comment]
@WizKid1968 I've updated the README to include deployment instructions.
