### ISSUE TITLE
Missing 'command' object in YAML

### ISSUE THREAD

**Issue by CodeMagic6** [zabirauf/AutoGPT.js#24]
Command Error: threw the following error: Missing 'command' object in YAML    How to resolve? I've established the website autogpt.js

**Comment by ticouto5290** [comment]
i've got the same issue anyone found a fix for it ?

**Comment by zabirauf** [comment]
@CodeMagic6 @ticouto5290 does refreshing and starting again often fix the issue?

**Comment by blumplan** [comment]
> @CodeMagic6 @ticouto5290 does refreshing and starting again often fix the issue?

Have it running on WSL Ubunti in dev mode and getting this error no matter what I do.

**Comment by tmikaeld** [comment]
Also getting the error, debian 11, nodejs 20 (upgraded remix)

**Comment by cutecharmingkid** [comment]
i've got the same issue

**Comment by sandeepscet** [comment]
Same issue  , tried in [autogptjs.com](https://autogptjs.com/)

**Comment by dmahlow** [comment]
Same here, any workarounds yet?

**Comment by christopherklint97** [comment]
> Same here, it seems to happen if you don't enter a valid OpenAI API key. Once I added a proper key the error went away.

Mhmm strange, I just tried it with a brand new API key and I got that error. Does not work to pause the chat either, just stuck looping the error.

![image](https://github.com/zabirauf/AutoGPT.js/assets/53100317/ea79ab17-215f-4593-b02f-1a999dda0138)

**Comment by cranyy** [comment]
Sadly, still getting this to this day. If any fixes have been found, would love to hear about them. P.S. This is a pretty awesome project, would be a shame to be abandonded.

**Comment by aklen** [comment]
I also got this problem - checked the dev console and realized from the error:
`
chunk-VFKPTDEB.js:1     POST https://api.openai.com/v1/chat/completions 429
chunk-VFKPTDEB.js:1 Error calling OpenAI service 429 {
    "error": {
        "message": "You exceeded your current quota, please check your plan and billing details.",
        "type": "insufficient_quota",
        "param": null,
        "code": "insufficient_quota"
    }
}
`
So in the case of getting 'Command Error: threw the following error: Missing 'command' object in YAML' please check the console logs!

**Comment by georgegeorge2525** [comment]
same here

**Comment by zabirauf** [comment]
#33 should fix it
