### ISSUE TITLE
Maybe we need a doc

### ISSUE THREAD

**Issue by Wenbobobo** [zabirauf/AutoGPT.js#6]
Applying AutoGPT to a browser is a excellent idea, but I am completely new and don't quite understand the relationship between the installation  steps in Readme and _autoGPtjs.com_ .  I hope there are kind-hearted people who can teach me, and I am also willing to participate in the writing of the document 😉

**Comment by zabirauf** [comment]
I agree that the info on website is lacking on how to use it. I'm planning to add steps on how to use it. Please share what would you like to see to make it helpful for you to use it?

**Comment by zabirauf** [comment]
@Wenbobobo I've added this to the autogptjs.com, does that help? 

![image](https://user-images.githubusercontent.com/1104560/232352248-72299326-843d-427e-8a59-298ba8c7a887.png)

**Comment by zabirauf** [comment]
Closing as added more info in README and also on website.
