### ISSUE TITLE
Users with only GPT3 would go into error

### ISSUE THREAD

**Issue by vecyang1** [zabirauf/AutoGPT.js#9]
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/130784544/232674593-530bcb7d-17b0-4628-bf28-10509c500c8c.png">

I only have GPT3 for now, and it stops. Could it work?

**Comment by zabirauf** [comment]
@vecyang1 yeah, I've also seen that sometimes this happens. Have you tried reloading the app and trying again, sometimes that helps fix it. 
Yesterday, I did make an improvement related to JSON parsing where newlines weren't being handled but it may not have caught all the issues. 
If you run into again, can you go please to dev tools and get the response from the latest `completions` API. I'll also see if I run into it next time.

**Comment by zabirauf** [comment]
@vecyang1 can you please try now. I've improved the parser, hoping that should fix this issue.
